site_name: ATLAS Analytics
pages:
    - Home: index.md
    - User Guides:
        - 'Elasticsearch & Kibana': 'user-guide/es_and_kibana.md'
        - 'Hadoop': 'user-guide/hadoop.md'
        - 'Spark': 'user-guide/spark.md'
        - 'Pig Latin': 'user-guide/pig.md'
        - 'Jupyter': 'user-guide/jupyter.md'
    - About: about.md
repo_url: https://github.com/ATLAS-Analytics/ATLAS-Analytics.github.io
# edit_uri: edit/master/
site_author: Ilija Vukotic
# google_analytics: ['UA-36723568-3', 'mkdocs.org']
remote_branch: master