site_name: ATLAS Analytics
pages:
    - Home: index.md
    - Data sources: 
        - 'Distributed Processing': 'data-sources/Distributed_processing.md'
        - 'FTS': 'data-sources/fts.md'
        - 'PerfSONAR': 'data-sources/perfsonar.md'
        - 'Benchmarks': 'data-sources/benchmarks.md'
        - 'xAOD': 'data-sources/xaod.md'
        - 'RTT': 'data-sources/rtt.md'
    - Infrastructure:
        - 'Computing': 'infrastructure/computing_nodes.md'
        - 'AMQ': 'infrastructure/amq.md'
        - 'Elasticsearch': 'infrastructure/elasticsearch.md'
        - 'Hadoop': 'infrastructure/hadoop.md'
        - 'Logstash': 'infrastructure/logstash.md'
    - User Guides:
        - 'Elasticsearch & Kibana': 'user-guide/es_and_kibana.md'
        - 'Hadoop': 'user-guide/hadoop.md'
        - 'Spark': 'user-guide/spark.md'
        - 'Pig Latin': 'user-guide/pig.md'
        - 'Jupyter': 'user-guide/jupyter.md'
    - About: about.md
repo_url: https://github.com/ATLAS-Analytics/ATLAS-Analytics
site_author: Ilija Vukotic
google_analytics: ['UA-3194765-3', 'ATLAS-Analytics']
# remote_branch: master